### Criar usuários [POST /v1/users]
Rota responsável por criar uma novo usuário na base de dados.

+ Request Criação de usuários (application/json)
    + Attributes
        <!-- include(../../requests/users/userStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/users/userStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
