### Atualizar usuários [PUT /v1/users]
Rota responsável por atualizar dados do usuário logado na aplicação.


+ Request Atualizar usuários (application/json)
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

    + Attributes
        <!-- include(../../data/userUpdate.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../data/userList.apib) -->

+ Response 400 (application/json)
    + Attributes
        + caso 1 (object)
            <!-- include(../../util/errorValidation.apib) -->
        + caso 2 (object)
            + error: Email is already in use
        + caso 3 (object)
            + error: This is your current email try another


+ Response 401 (application/json)
    + Attributes
        + caso 1 (object)
            <!-- include(../../util/errorTokenNotProvided.apib) -->
        + caso 2 (object)
            + error: Password does not match

+ Response 404 (application/json)
    + Attributes
        + error: User not found

