### Listar usuários [GET /v1/users]
Rota responsável por listar todos os usuários

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../data/userList.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->
