### Listar usuários [GET /v1/users]
Rota responsável por listar todos os usuários

+ Request Bearer Token
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../data/userList.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->
