### Excluir usuários [DELETE /v1/users/{id}]
Rota responsável por excluir usuários do sistema.

+ Parameters
    + id: id (number, required) - ID do usuário

+ Request Bearer Token
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 204 (No content)

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->

+ Response 404 (application/json)
    + Attributes
        + error: User not found
