### Criar usuário [POST /v1/users]
Rota responsável por criar uma novo usuário na base de dados.

+ Request Criação de usuário (application/json)
    + Attributes
        <!-- include(../../requests/userStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/userStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
