### Listar todas as ferramentas [GET /v1/tools]
Rota responsável por listar todas as ferramentas

+ Request Bearer Token
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../data/toolList.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->
