### Criar ferramentas [POST /v1/tools]
Rota responsável por criar uma nova ferramenta na base de dados.

+ Request Criação de ferramentas (application/json)
    + Attributes
        <!-- include(../../requests/tools/toolStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/tools/toolStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
