### Listar todas as ferramentas [GET /v1/tools]
Rota responsável por listar todas as ferramentas

+ Response 200 (application/json)
    + Attributes
        <!-- include(../../data/toolList.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->
