### Criar ferramentas [POST /v1/tools]
Rota responsável por criar uma nova ferramenta na base de dados.

+ Request Criação de ferramentas (application/json)
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

    + Attributes
        <!-- include(../../data/toolRequired.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../data/toolOptional.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->

+ Response 404 (application/json)
    + Attributes
        + error: Icon not found
