### Excluir ferramentas [DELETE /v1/tools/{id}]
Rota responsável por excluir ferramentas do sistema pelo seu id.

+ Parameters
    + id: id (number, required) - ID da ferramenta

+ Request Deletar ferramenta
    + Headers

            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==

+ Response 204 (No content)

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->

+ Response 404 (application/json)
    + Attributes
        + error: Tool not found
