### Upload de ícones [POST /v1/icons]
Rota responsável por fazer upload de ícones no sistema.

+ Request Upload de ícones (multipart/form-data)
    + Attributes
        <!-- include(../../data/iconCreate.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../data/iconList.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->
