### Deletar ícones [DELETE /v1/icons/{id}]
Rota responsável por excluir ícones do sistema.

+ Parameters
    + id: id (number, required) - ID do ícone

+ Response 204 (No content)

+ Response 401 (application/json)
    + Attributes
        <!-- include(../../util/errorTokenNotProvided.apib) -->

+ Response 404 (application/json)
    + Attributes
        + error: Icon not found
