### Upload de ícone [POST /v1/icons]
Rota responsável por fazer upload de ícones no sistema.

+ Request Upload de ícones (application/json)
    + Attributes
        <!-- include(../../requests/iconStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/iconStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
