### Upload de ícones [POST /v1/icons]
Rota responsável por fazer upload de ícones no sistema.

+ Request Upload de ícones (multipart/form-data)
    + Attributes
        <!-- include(../../requests/icons/iconStore.apib) -->

+ Response 201 (application/json)
    + Attributes
        <!-- include(../../responses/icons/iconStore.apib) -->

+ Response 400 (application/json)
    + Attributes
        <!-- include(../../util/errorValidation.apib) -->
