### Descrição

+ A API desenvolvida tem por objetivo principal, armazenar as ferramentas mais utilizadas por usuários, sendo possível pesquisá-las por usuário que as cadastrou e/ou tags de referência.

+ Possui também cadastro e autenticação de usuários, sendo obrigatório para cadastrar e gerenciar novas ferramentas na plataforma.

+ No momento da criação de uma nova ferramenta, é possível incluir um ícone que represente a mesma para melhor identificação visual.

+ Usuários podem pesquisar outros usuários por tecnologias que trabalham, tendo a possibilidade de criarem uma 'rede' de relacionamento profissional a partir da aplicação.

### Token de Autenticação

+ Um token do tipo **(Bearer Token)** é necessário para algumas operações de usuários na API, o mesmo é gerado quando um usuário realiza log in na aplicação.
