### Descrição

+ A API desenvolvida tem por objetivo principal, armazenar as ferramentas mais utilizadas, sendo possível listá-las e pesquisá-las por tags de referência.

+ Possui também cadastro e autenticação e usuários, sendo obrigatório para cadastrar e gerenciar novas ferramentas na plataforma.

+ No momento da criação de uma nova ferramenta, é possível incluir um ícone que represente a mesma para melhor identificação visual.
