FORMAT: 1A

# Documentação - VUTTR BossaBox

API para cadastro de ferramentas mais utilizadas pela BossaBox.

<!-- include(routes/sessions/index.apib) -->
<!-- include(routes/users/index.apib) -->
<!-- include(routes/icons/index.apib) -->
<!-- include(routes/tools/index.apib) -->
