FORMAT: 1A

# Documentação - VUTTR BossaBox V1

***:wrench: (VUTTR - VERY USEFUL TOOLS TO REMEMBER) :wrench:***



<!-- include(routes/overview/index.apib) -->
<!-- include(routes/sessions/index.apib) -->
<!-- include(routes/users/index.apib) -->
<!-- include(routes/icons/index.apib) -->
<!-- include(routes/tools/index.apib) -->
<!-- include(routes/errors/index.apib) -->

