### Rota inválida [GET /v1/invalidroute]
Exemplo de resposta para requisições em rotas não existentes na aplicação.

+ Response 404 (application/json)
    + Attributes
        + error: Route not found
