### Rota inválida [GET /v1/invalidroute]

+ **Modelo de resposta para requisições em rotas não existentes na aplicação.**
    + **Obs:** Para todos os métodos HTTP - **(GET/POST/PUT/DELETE)**

+ Response 404 (application/json)
    + Attributes
        <!-- include(../../util/errorNotFound.apib) -->
